### ISSUE TITLE
Error：KeyError: './preprocess_files/comparisons.reformatted.txt'

### ISSUE THREAD

**Issue by haonanduanmu** [sjroth/ARTDeco#11]
I have used environment.yml to construct a conda environment named ARTDeco. But when I use ARTDeco to predict readthrough using preprocess mode, I get an error like this.

Loading ARTDeco file structure...
Traceback (most recent call last):
  File "/home/miniconda3/envs/ARTDeco/bin/ARTDeco", line 33, in <module>
    sys.exit(load_entry_point('ARTDeco==0.4', 'console_scripts', 'ARTDeco')())
  File "/home/miniconda3/envs/ARTDeco/lib/python3.6/site-packages/ARTDeco-0.4-py3.6.egg/ARTDeco/main.py", line 222, in main
  File "/home/miniconda3/envs/ARTDeco/lib/python3.6/site-packages/ARTDeco-0.4-py3.6.egg/ARTDeco/misc.py", line 223, in get_files
KeyError: './preprocess_files/comparisons.reformatted.txt'

Here is my command
ARTDeco -mode preprocess -gtf-file /home/duanmu/project/Dme/00_genome/dm6.ncbiRefSeq.gtf -chrom_size-file /home/duanmu/project/Dme/00_genome/genome.chrom.sizes -bam-files-dir /home/duanmu/project/Dme/01_bam/

Plz help me to solve this. Thank u!

**Comment by haonanduanmu** [comment]
Oh,I found there is a same question in the closed issue!

**Comment by sjroth** [comment]
Hi @haonanduanmu, I am happy to help. For the sake of continuity, please try not to edit posts and change their titles. It makes it confusing for me.

It seems that your error revolves around the fact that preprocess files requires a meta file for experimental set up. If you are not conducting a differential analysis, I would specify your terminal mode.

**Comment by haonanduanmu** [comment]
Hi, I had a problem earlier which had been solved in the closed issue. So, I edited the issue wanting to solve another probelm I met. 
Do you mean that I only need to use the command below if I do not have a meta file?
ARTDeco  -bam-files-dir BAM_FILES_DIR -gtf-file GTF_FILE -cpu NUM_CPU -chrom-sizes-file CHROM_SIZES_FILE

**Comment by sjroth** [comment]
Or use -mode readthrough or -mode DoGs. The preprocess mode has a bug where it requires the DESeq2 input. I may edit this down the line.

**Comment by haonanduanmu** [comment]
OK, thank you! I wiil try it. 
But if I do not use preprocess mode, I won't have preprocessing files. Does the follow command work?

**Comment by sjroth** [comment]
As explained in the README, ARTDeco will automatically regenerate all necessary files. You did not include a command.

**Comment by haonanduanmu** [comment]
Oh, I fotget it. Thank you!
By the way, your ARTDeco helps me a lot!

**Comment by sjroth** [comment]
You're welcome. I designed ARTDeco so that the user has to do minimal file management. I may recode the preprocess mode if this error comes up again. Thank you for noting it!

**Comment by J-Netherton** [comment]
Hi @sjroth, I've also had this error. 

> `Error：KeyError: './preprocess_files/comparisons.reformatted.txt'`

As you've stated above, it's solved by having a meta file.
