### ISSUE TITLE
problem in installing ARTDeco

### ISSUE THREAD

**Issue by Drosofriends** [sjroth/ARTDeco#16]
Hi, 
I'm trying to install artdeco but I have many problems in doing it. When I launch python setup.py install this error occured:
canceled (core dump created). What kind of problem is this?
Moreover, I'm not able to download the required packages because the conda env create -f environment.yml does not work. So I manually downloaded the packages but beacuse of conflicts I have many problems in terms of versions. 
Any help?
thanks for the support!

**Comment by sjroth** [comment]
Hi,

If you are not able to use the conda environment, I recommend trying to install the individual software tools with the correct version so they do not clash. I cannot help with software incompatibilities as I do not have access to your system.

**Comment by Drosofriends** [comment]
I created a new empty enviroment and than I install python version 3.6 and than i run the following command:
conda install -c bioconda bedops=2.4.* bioconductor-deseq2=1.20.* bx-python=0.8.* homer=4.9.* networkx=2.* numpy=1.16.* pandas=0.24.* pybigwig rpy2=2.9.* rseqc=3.0.* samtools=1.9
But i had a lot of conflicts and only bedops installed.

**Comment by sjroth** [comment]
Again, without access to your machine, it’s hard for me to help. You are probably using a newer version of conda, which is known to have conflicts with R packages. I would try installing packages one at a time.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Drosofriends** [comment]
I solved the problem by using mamba and the .yml file for the installation. Thank you for the help.
I close this issue!
