### ISSUE TITLE
How does ARTDeco Handles multi-mapped reads?

### ISSUE THREAD

**Issue by paulocaldas** [sjroth/ARTDeco#18]
Hi,

I have just a quick question. I was trying to figure out how ARTDeco deals with multimapped reads in the bam files?

The reason this is relevant for me is because I tried to run ARTDeco on 100+ bam files aligned with STAR using the option --outFilterMultimapNmax set to 10 (default) and then set to 1 (only allowing for unique aligned reads) and I got roughly the same number of expressed genes and number of DoGs. I'm tryin to figure out the reason the results don't change at all (which is actually not a bad thing if it the case)

Cheers,
Paulo

**Comment by sjroth** [comment]
Hi Paulo,

Multimappers are handled by HOMER. When creating a tag directory (the basic data structure of reads), by default, multimappers are tossed out (only uniquely mapped reads are used; description here: http://homer.ucsd.edu/homer/ngs/tagDir.html). This is part of the difference in performance between DoGFinder and ARTDeco. 

Hope this helps,
Sam

**Comment by paulocaldas** [comment]
Great! Thanks for the quickly reply ;)
