### ISSUE TITLE
KeyError: './preprocess_files/comparisons.reformatted.txt'

### ISSUE THREAD

**Issue by njlxalan** [sjroth/ARTDeco#20]
When I  run preprocessing using the following command:
ARTDeco -mode preprocess -gtf-file modified_genes.gtf -chrom-sizes-file genome.chrom.sizes 
it showed the error  "File "//anaconda3/envs/ARTDeco/bin/ARTDeco", line 33, in <module>
    sys.exit(load_entry_point('ARTDeco==0.4', 'console_scripts', 'ARTDeco')())
  File "//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/ARTDeco-0.4-py3.6.egg/ARTDeco/main.py", line 222, in main
  File "//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/ARTDeco-0.4-py3.6.egg/ARTDeco/misc.py", line 223, in get_files
KeyError: './preprocess_files/comparisons.reformatted.txt'"
Any help?
thanks

**Comment by sjroth** [comment]
Hi @njlxalan,

This error is due to the fact that you are running preprocess mode without a meta file or a comparisons file. I recommend running readthrough mode if you do not have these files.

Best,
Sam

**Comment by njlxalan** [comment]
thanks. But after running readthrough and get_dogs mode , I still do not have meta file or a comparisons file in Preprocessing files.
How can I get meta file or a comparisons file which is needed for "Differential Expression with Read-In Information mode"
thanks
njlxalan

**Comment by njlxalan** [comment]
Readthrough and get_dogs mode  are both successful, but when I run  -mode diff_exp_read_in
error happened.

//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Error: package or namespace load failed for ‘S4Vectors’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/anaconda3/envs/ARTDeco/lib/R/library/S4Vectors/libs/S4Vectors.so':
  dlopen(/anaconda3/envs/ARTDeco/lib/R/library/S4Vectors/libs/S4Vectors.so, 6): Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /anaconda3/envs/ARTDeco/lib/R/library/S4Vectors/libs/S4Vectors.so
  Reason: image not found
warnings.warn(x, RRuntimeWarning)
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Failed with error:  
  warnings.warn(x, RRuntimeWarning)
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: 
  warnings.warn(x, RRuntimeWarning)
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: ‘package ‘S4Vectors’ could not be loaded’
  warnings.warn(x, RRuntimeWarning)
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: 

  warnings.warn(x, RRuntimeWarning)
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/anaconda3/envs/ARTDeco/lib/R/library/BiocParallel/libs/BiocParallel.so':
  dlopen(/anaconda3/envs/ARTDeco/lib/R/library/BiocParallel/libs/BiocParallel.so, 6): Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /anaconda3/envs/ARTDeco/lib/R/library/BiocParallel/libs/BiocParallel.so
  Reason: image not found
any help thanks

**Comment by sjroth** [comment]
Hi,

As explained in the README, you need to provide the meta file and the comparisons file. File formats and examples are described in the documentation.

Best,
Sam

**Comment by njlxalan** [comment]
Hi Sam
Thanks.  I generated the meta file and the comparisons file.  but when I run ARTDeco -mode diff_exp_read_in -meta-file meta.txt.      Error happened.  My system is macOS. Readthrough and get_dogs mode both works for me.

Running diff_exp_read_in mode...
Loading ARTDeco file structure...
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Error: package or namespace load failed for ‘S4Vectors’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/anaconda3/envs/ARTDeco/lib/R/library/S4Vectors/libs/S4Vectors.so':
  dlopen(/anaconda3/envs/ARTDeco/lib/R/library/S4Vectors/libs/S4Vectors.so, 6): Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /anaconda3/envs/ARTDeco/lib/R/library/S4Vectors/libs/S4Vectors.so
  Reason: image not found

  warnings.warn(x, RRuntimeWarning)
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Failed with error:  
  warnings.warn(x, RRuntimeWarning)
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: 
  warnings.warn(x, RRuntimeWarning)
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: ‘package ‘S4Vectors’ could not be loaded’
  warnings.warn(x, RRuntimeWarning)
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: 

  warnings.warn(x, RRuntimeWarning)
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/anaconda3/envs/ARTDeco/lib/R/library/BiocParallel/libs/BiocParallel.so':
  dlopen(/anaconda3/envs/ARTDeco/lib/R/library/BiocParallel/libs/BiocParallel.so, 6): Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /anaconda3/envs/ARTDeco/lib/R/library/BiocParallel/libs/BiocParallel.so
  Reason: image not found

  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File "//anaconda3/envs/ARTDeco/bin/ARTDeco", line 33, in <module>
    sys.exit(load_entry_point('ARTDeco==0.4', 'console_scripts', 'ARTDeco')())
  File "//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/ARTDeco-0.4-py3.6.egg/ARTDeco/main.py", line 115, in main
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/ARTDeco-0.4-py3.6.egg/ARTDeco/DESeq2.py", line 12, in <module>
  File "//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/robjects/packages.py", line 453, in importr
    env = _get_namespace(rname)
rpy2.rinterface.RRuntimeError: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/anaconda3/envs/ARTDeco/lib/R/library/BiocParallel/libs/BiocParallel.so':
  dlopen(/anaconda3/envs/ARTDeco/lib/R/library/BiocParallel/libs/BiocParallel.so, 6): Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /anaconda3/envs/ARTDeco/lib/R/library/BiocParallel/libs/BiocParallel.so
  Reason: image not found

**Comment by sjroth** [comment]
That is an issue with your installation of your R packages (something I want to set aside time to refactor when I have more bandwidth). Can you verify the installation of DESeq2 within an R environment?

**Comment by njlxalan** [comment]
Yes, I installed DESeq2 within an R environment. But after that Error still happened.  Do I need to install ARTDeco again after installing DESeq2 in R?

ARTDeco -mode diff_exp_read_in -meta-file meta.txt. . 
Running diff_exp_read_in mode...
Loading ARTDeco file structure...
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/init.py:146: RRuntimeWarning: Error: package or namespace load failed for ‘S4Vectors’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/anaconda3/envs/ARTDeco/lib/R/library/S4Vectors/libs/S4Vectors.so':
dlopen(/anaconda3/envs/ARTDeco/lib/R/library/S4Vectors/libs/S4Vectors.so, 6): Library not loaded: @rpath/libgfortran.3.dylib
Referenced from: /anaconda3/envs/ARTDeco/lib/R/library/S4Vectors/libs/S4Vectors.so
Reason: image not found

warnings.warn(x, RRuntimeWarning)
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/init.py:146: RRuntimeWarning: Failed with error:
warnings.warn(x, RRuntimeWarning)
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/init.py:146: RRuntimeWarning:
warnings.warn(x, RRuntimeWarning)
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/init.py:146: RRuntimeWarning: ‘package ‘S4Vectors’ could not be loaded’
warnings.warn(x, RRuntimeWarning)
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/init.py:146: RRuntimeWarning:

warnings.warn(x, RRuntimeWarning)
//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/rinterface/init.py:146: RRuntimeWarning: Error in dyn.load(file, DLLpath = DLLpath, ...) :
unable to load shared object '/anaconda3/envs/ARTDeco/lib/R/library/BiocParallel/libs/BiocParallel.so':
dlopen(/anaconda3/envs/ARTDeco/lib/R/library/BiocParallel/libs/BiocParallel.so, 6): Library not loaded: @rpath/libgfortran.3.dylib
Referenced from: /anaconda3/envs/ARTDeco/lib/R/library/BiocParallel/libs/BiocParallel.so
Reason: image not found

warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
File "//anaconda3/envs/ARTDeco/bin/ARTDeco", line 33, in
sys.exit(load_entry_point('ARTDeco==0.4', 'console_scripts', 'ARTDeco')())
File "//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/ARTDeco-0.4-py3.6.egg/ARTDeco/main.py", line 115, in main
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 656, in _load_unlocked
File "", line 626, in _load_backward_compatible
File "//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/ARTDeco-0.4-py3.6.egg/ARTDeco/DESeq2.py", line 12, in
File "//anaconda3/envs/ARTDeco/lib/python3.6/site-packages/rpy2/robjects/packages.py", line 453, in importr
env = _get_namespace(rname)
rpy2.rinterface.RRuntimeError: Error in dyn.load(file, DLLpath = DLLpath, ...) :
unable to load shared object '/anaconda3/envs/ARTDeco/lib/R/library/BiocParallel/libs/BiocParallel.so':
dlopen(/anaconda3/envs/ARTDeco/lib/R/library/BiocParallel/libs/BiocParallel.so, 6): Library not loaded: @rpath/libgfortran.3.dylib
Referenced from: /anaconda3/envs/ARTDeco/lib/R/library/BiocParallel/libs/BiocParallel.so
Reason: image not found

**Comment by sjroth** [comment]
The error is with your R installation in that conda environment. Can you verify whether it is properly installed within R?

To further explain, your error seems to be referring to an error in loading the underlying C and Fortran libraries in R, but I cannot debug that from here.

**Comment by njlxalan** [comment]
thanks, which version of R-base is suggested to be installed by conda? my current R-base version is 3.5.1

**Comment by sjroth** [comment]
I don't know if it is a versioning error. That is why I am asking if you can load the package in an R interpretative environment. What do you get when you type the following command?
```
which R
```

**Comment by njlxalan** [comment]
get this 
//anaconda3/envs/ARTDeco/bin/R

**Comment by sjroth** [comment]
Okay, so your R interpreter is correct. Can you enter an interactive R shell and see if DESeq2 is installed?

**Comment by njlxalan** [comment]
yes. DEseq2 is installed.DESeq2               
DESeq2   "/anaconda3/envs/ARTDeco/lib/R/library" "1.20.0" 
but do not know the meaning below:
DESeq2    "S4Vectors (>= 0.9.25), IRanges, GenomicRanges,\nSummarizedExperiment (>= 1.1.6)"

**Comment by sjroth** [comment]
Did you go into an active R shell and type
```
library(DESeq2)
```
Again, from the error message above, the issue is with running DESeq2 and your R installation. Are you absolutely sure that you need to run the diff_exp modes? What is your level of experience with programming and package management in R?

**Comment by njlxalan** [comment]
it seems error for some package.i'm really a freshman of package management in R.
> library(DESeq2)
Loading required package: S4Vectors
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colMeans,
    colnames, colSums, dirname, do.call, duplicated, eval, evalq,
    Filter, Find, get, grep, grepl, intersect, is.unsorted, lapply,
    lengths, Map, mapply, match, mget, order, paste, pmax, pmax.int,
    pmin, pmin.int, Position, rank, rbind, Reduce, rowMeans, rownames,
    rowSums, sapply, setdiff, sort, table, tapply, union, unique,
    unsplit, which, which.max, which.min

Error: package or namespace load failed for ‘S4Vectors’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/anaconda3/envs/ARTDeco/lib/R/library/S4Vectors/libs/S4Vectors.so':
  dlopen(/anaconda3/envs/ARTDeco/lib/R/library/S4Vectors/libs/S4Vectors.so, 6): Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /anaconda3/envs/ARTDeco/lib/R/library/S4Vectors/libs/S4Vectors.so
  Reason: image not found
Error: package ‘S4Vectors’ could not be loaded
>

**Comment by sjroth** [comment]
Yes, this is what I was trying to highlight earlier. I think you need to iron out why S4Vectors isn't working. This is beyond the scope of what I can help with in a reasonable time.

**Comment by njlxalan** [comment]
thanks a lot for your help.
