### ISSUE TITLE
Package Directory ARTDeco Does not Exist

### ISSUE THREAD

**Issue by faleevz** [sjroth/ARTDeco#21]
Hi there! My apologies if its a bit of a stupid question- I am just starting out with conda. 
I am trying to download ARTDeco but unfortunately hit an error when I try to install setup.py 

I have downloaded all the necessary packages apart from DEseq2. 
When I try to pass 
`python setup.py install ` in the folder that contains the setup.py file, it shows me an error of: 

`running install
/Users/faleevz/anaconda3/envs/py37/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/Users/faleevz/anaconda3/envs/py37/lib/python3.7/site-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing ARTDeco.egg-info/PKG-INFO
writing dependency_links to ARTDeco.egg-info/dependency_links.txt
writing entry points to ARTDeco.egg-info/entry_points.txt
writing requirements to ARTDeco.egg-info/requires.txt
writing top-level names to ARTDeco.egg-info/top_level.txt
error: package directory 'ARTDeco' does not exist`

I have also tried to manually make a directory before running the command. 
Each time it successfully downloads the ARTDeco.egg-info folder, but nothing else. Commands are not available. 

I'd greatly appreciate your help! Many thanks

**Comment by faleevz** [comment]
Otherwise, if I manually add a folder, it does install several files (including build, dist), but the ARTDeco -h command does not run, saying that there is no ARTDeco module.

**Comment by sjroth** [comment]
Hi,

Have you tried the instructions as laid out in the README?

**Comment by faleevz** [comment]
Hi, I have. Here is my code below:
```
conda env create -f environment.yml
Downloading and Extracting Packagess                                                                          
Preparing transaction: done                                                     
Verifying transaction: done                                                     
Executing transaction: done                                                                                                                                
# To activate this environment, use                                                                                                             
#     $ conda activate ARTDeco                                                  
#                                                                               
# To deactivate an active environment, use                                      
#                                                                               
#     $ conda deactivate                                                        
                                                                                
(py37) MA57747:Desktop faleevz$ conda activate ARTDeco                   
(ARTDeco) MA57747:Dekstop faleevamaria$ python setup.py install               
running install                                                                 
running bdist_egg                                                               
running egg_info                                                                
creating ARTDeco.egg-info                                                       
writing ARTDeco.egg-info/PKG-INFO                                               
writing dependency_links to ARTDeco.egg-info/dependency_links.txt               
writing entry points to ARTDeco.egg-info/entry_points.txt                       
writing requirements to ARTDeco.egg-info/requires.txt                           
writing top-level names to ARTDeco.egg-info/top_level.txt
writing manifest file 'ARTDeco.egg-info/SOURCES.txt'
error: package directory 'ARTDeco' does not exist' 
```
Your help would be greatly appreciated!

**Comment by faleevz** [comment]
Figured it out! For anyone who may be struggling- download the entire ARTDeco package from the github repository. Also the python setup.py install has been deprecated, using 
```python -m pip install . ``` worked for me.
