### ISSUE TITLE
May I ask how to resolve this error

### ISSUE THREAD

**Issue by ChenXi1201** [sjroth/ARTDeco#29]
![image](https://github.com/user-attachments/assets/85e98a5a-9afd-4be2-af7b-cf562e874083)

**Comment by sjroth** [comment]
Hi,

This looks like a BAM file formatting issue. Can you run RSeQC on your BAM files?

**Comment by ChenXi1201** [comment]
您的来信已收到，我会尽快查看，谢谢陈曦

**Comment by sjroth** [comment]
I'm sorry. I don't read that language.
