### ISSUE TITLE
Filter ARTDeco output for non-stranded RNA-seq samples？

### ISSUE THREAD

**Issue by ChenXi1201** [sjroth/ARTDeco#30]
The operation mentioned in the literature that cites ARTDeco, which involves using bedtools to filter out potential false positives caused by the expression of genes on the opposite strand, is considered necessary by some researchers. This step is taken to ensure that the list of readthrough transcripts identified by ARTDeco is as accurate and robust as possible.
![image](https://github.com/user-attachments/assets/11c0f486-0ee8-4fd7-9d89-242aabf5f601)
I am not particularly familiar with the specific algorithms of the ARTDeco. Is this operation necessary? Did ARTDeco not consider the impact of gene expression on the opposite strand in its design?

**Comment by sjroth** [comment]
Hi,

It seems you have misread the very screenshot you provided. ARTDeco cannot infer strandedness out of a non-stranded library. This is an issue with the RNA-seq prep and not ARTDeco. In general, I recommend against inferring DoGs in the case of non-stranded data because it leads to problematic data interpretation.

Best,
Sam

**Comment by ChenXi1201** [comment]
您的来信已收到，我会尽快查看，谢谢陈曦

**Comment by ChenXi1201** [comment]
Thank you very much!



---Original---
From: ***@***.***&gt;
Date: Wed, Sep 18, 2024 21:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sjroth/ARTDeco] Filter ARTDeco output for non-stranded RNA-seq samples？ (Issue #30)




 
Hi,
 
It seems you have misread the very screenshot you provided. ARTDeco cannot infer strandedness out of a non-stranded library. This is an issue with the RNA-seq prep and not ARTDeco. In general, I recommend against inferring DoGs in the case of non-stranded data because it leads to problematic data interpretation.
 
Best,
 Sam
