### ISSUE TITLE
Only DoGs for DESeq

### ISSUE THREAD

**Issue by Bridream** [sjroth/ARTDeco#34]
Hi,
ARTDeco seems to use DoG raw counts as input to DESeq2 for differential DoG expression analysis. I wonder if this fits in DESeq2 model, because DESeq2 needs to see a lot of genes to estimate dispersion and library size for each sample. But DoGs comprise only a small part of the transcriptome. Another method, Dogcatcher, uses other genes along with DoGs to perform DESeq analysis. I am not sure whether using only DoGs for DESeq2 is proper or not.
Looking forward to your reply. Thank you very much.

**Comment by sjroth** [comment]
Hi @Bridream,

I believe that the bigger concern is that the transcript models for DoGs are relatively crude and naive (for example, there is anecdotal evidence that there are cryptic splice sites within longer DoGs and coverage is relatively uneven). Personally, I am not a fan of this function and it was added on as a feature request. I would steer clear of this functionality except in the most extreme circumstances.
