### ISSUE TITLE
Metafile not properly formatted

### ISSUE THREAD

**Issue by pillailab** [sjroth/ARTDeco#5]
I am running the process mode and my bam file list looks like below:
MPR85_STAR_Aligned.sortedByCoord.out.bam  
MPR86_STAR_Aligned.sortedByCoord.out.bam  
MPR90_STAR_Aligned.sortedByCoord.out.bam
MPR91_STAR_Aligned.sortedByCoord.out.bam

I formatted the metafile.txt as below:
Experiment      Group
MPR85_R1        WT_Total
MPR86_R2        WT_Total
MPR90_R1        Mut_Total
MPR91_R2        Mut_Total
When i run the preprocess command as below:
ARTDeco -mode preprocess -gtf-file modified_gencode.v22.annotation.gtf.gtf -chrom-sizes-file GRCh38.genome.chrom.sizes -home-dir ~/scratch60/SF3B1_PRC2/March_2021/ARTDeco -bam-files-dir ~/scratch60/SF3B1_PRC2/March_2021/ARTDeco/bam/ -cpu 1 -meta-file ~/scratch60/SF3B1_PRC2/March_2021/ARTDeco/meta.txt 
I get the following error:
Running preprocess mode...
Loading ARTDeco file structure...
Meta file not properly formatted... Exiting...

The format for metafile is not very clear - what am i doing wrong ?
thanks
Manoj

**Comment by sjroth** [comment]
Hi Manoj,

Your labels are not consistent with your bam file names. ARTDeco takes the prefix (everything before the .bam extension) as the name for the experiment. You need to either rename your files or rename the experiments.

Best,
Sam

**Comment by pillailab** [comment]
wow - fast response ! that worked - thanks a lot.
Manoj

**Comment by tud03125** [comment]
I also have the same issue (currently). My META and COMPARISON TSV files are these:

```
(/rs01/projects/jadezhoulab/tud03125/anaconda3/envs/dott_pipeline_Temple/ARTDeco) [levinm@fchpclogprd01 ~]$ head -n 10 /rs01/projects/jadezhoulab/tud03125/GSE59717/ARTDeco_HSV1_run/meta.tsv                                                                               
sample  condition
SRR1523658_Aligned.sortedByCoord.out    uninfected
SRR1523672_Aligned.sortedByCoord.out    uninfected
SRR1523666_Aligned.sortedByCoord.out    HSV1
SRR1523680_Aligned.sortedByCoord.out    HSV1
(/rs01/projects/jadezhoulab/tud03125/anaconda3/envs/dott_pipeline_Temple/ARTDeco) [levinm@fchpclogprd01 ~]$ head -n 10 /rs01/projects/jadezhoulab/tud03125/GSE59717/ARTDeco_HSV1_run/comparisons.tsv                                                                        
condition1      condition2
HSV1    uninfected
(/rs01/projects/jadezhoulab/tud03125/anaconda3/envs/dott_pipeline_Temple/ARTDeco) [levinm@fchpclogprd01 ~]$
```

I was running this code:

```
ARTDeco \
  -home-dir /rs01/projects/jadezhoulab/tud03125/GSE59717/ARTDeco_HSV1_run \
  -bam-files-dir /rs01/projects/jadezhoulab/tud03125/GSE59717/ARTDeco_HSV1_run/bams \
  -gtf-file /rs01/projects/jadezhoulab/tud03125/pipeline/hg38.knownGene.gtf \
  -chrom-sizes-file /rs01/projects/jadezhoulab/tud03125/pipeline/hg38.chrom.sizes \
  -cpu 8 \
  -meta-file /rs01/projects/jadezhoulab/tud03125/GSE59717/ARTDeco_HSV1_run/meta.tsv \
  -comparisons-file /rs01/projects/jadezhoulab/tud03125/GSE59717/ARTDeco_HSV1_run/comparisons.tsv
```

**Comment by nanu23333** [comment]
I met the same error! Did you figure out?

**Comment by tud03125** [comment]
I actually did! Two things:

- For Meta data, ARTDeco didn't accept "sample  condition" columns, even though that's in their example. Looking inside their "main.py" pipeline, what should've been the right header was these: "Experiment   Group."
- Comparison one wasn't the big issue. But, I found better success (especially ensuring proper comparisons) when "condition1      condition2" header was actually removed, and that it's just one line, which's "HSV1    uninfected," and that's it.

I also noticed that after running that ARTDeco run successfully, the Read-In Assignments was missing. So, I had to force-add by `printf "Gene ID\tGene Type\n" > "${RUN_DIR}/preprocess_files/gene_types.txt"`, and then re-run ARTDeco in `-mode diff_exp_read_in` without `-overwrite` parameter so that the Read-In Assignments would be properly produced.

**Comment by sjroth** [comment]
Hi @tud03125,

I am glad that you found the solution. I would caution that you follow examples as "Experiment Group" was the header in the sample input (you were mistaken on that). It has been many years but I was very particular on formatting those inputs.

**Comment by tud03125** [comment]
@sjroth Oh you're right! You did those in your sample inputs. Must have missed seeing these.

**Comment by nanu23333** [comment]
Sorry to bother, but actually I did not see any input file format sample in readme file. Could you please show me?

**Comment by tud03125** [comment]
@nanu23333 It's not inside README. It's in "SampleInputs" folder. If you open them, you'll see two links: `comparison.txt` (https://github.com/sjroth/ARTDeco/blob/master/SampleInputs/comparisons.txt) and `meta.txt` (https://github.com/sjroth/ARTDeco/blob/master/SampleInputs/meta.txt).

**Comment by nanu23333** [comment]
> [@nanu23333](https://github.com/nanu23333) It's not inside README. It's in "SampleInputs" folder. If you open them, you'll see two links: `comparison.txt` (https://github.com/sjroth/ARTDeco/blob/master/SampleInputs/comparisons.txt) and `meta.txt` (https://github.com/sjroth/ARTDeco/blob/master/SampleInputs/meta.txt).

thx a lot!
