### ISSUE TITLE
ARTDeco gets stuck generating expression data in FPKMs

### ISSUE THREAD

**Issue by paulocaldas** [sjroth/ARTDeco#8]
So far I've been running ARTDeco with almost no problems, but when I have too many samples (in this example 200) ARTDeco gets stuck in the last step (image below). It has been like this for 4 days now ... It's probably due to the number of samples, but it's strange that ARTDeco can still generate the individual FPKM files, but not the all_dogs file.

![image](https://user-images.githubusercontent.com/49621351/150508850-18118e62-2e3c-480f-8260-be573788abce.png)

**Comment by sjroth** [comment]
When reporting issues, can you also include your command? It makes it easier to debug.

This behavior is not strange if you are running out of RAM during this operation. There are other command line options for this that are less memory intensive, though slower, than this. Can you confirm that the individual FPKM files are generated?

**Comment by paulocaldas** [comment]
This was my command:
ARTDeco -home-dir /artdeco_results/ -bam-files-dir /bam_files/ -gtf-file human.modified.annotation.file.gencodev37.gtf -cpu 8 -chrom-sizes-file human.genome.chrom.sizes -min-dog-len 2000 -dog_window 200 -min_dog_coverage 0.2.

and yes, the other files are being generated. Here's the "head" of the file inside the dogs folder 
![image](https://user-images.githubusercontent.com/49621351/150585990-274d5709-eb0e-4d3b-9bb4-2853515773df.png)

Should I use more cores in the -cpu parameter or there's a different option to use less memory (even if it is slower)
I've working with datasets of 50 to 120 samples until now. Everything went fine. 
but now with roughly 200 ARTDeco gets stuck.

**Comment by sjroth** [comment]
I would use more CPUs if possible and try again. Is ARTDeco generating temporary files for expression quantification? And can you monitor the processing to ensure that it is calling HOMER's annotatePeaks function?

**Comment by paulocaldas** [comment]
at this point (when stuck at that last step) it doesn't seem to be calling anything. Also, the /tmp folder is empty. 
I hope I'm checking it right. 
I will try again with more memory now.
It will try to create only the files missing, which are two...

![image](https://user-images.githubusercontent.com/49621351/150590651-7d6a4c8f-ce90-4483-8910-accf4a445f19.png)

**Comment by paulocaldas** [comment]
Hi again @sjroth
just for the record, I didn't forget about this, but the computer cluster that I use has been super busy, and I can't use so much memory at once without affecting other people's work. I will still try if using 16 cores can overcome this issue. 
However, in the meantime I'm having another problem, but I will open a different issue for that.

**Comment by paulocaldas** [comment]
@sjroth I finally got the chance to use more RAM and run 190 samples at once. ARTDeco worked like a charm!
It's odd that ARTDeco still managed to generate all the individual dog files before, except the all_dogs.fpkm (where he got stuck for days) but (much) more RAM was the solution.

**Comment by sjroth** [comment]
Awesome! I'm very happy that it worked. I'm not surprised memory was the issue as these processes can be leaky when aggregating lots of samples. One day I'll have to benchmark the memory usage in order to inform what resources are demanded.
